### ISSUE TITLE
Caches no longer work with intensity maps

### ISSUE THREAD

**Issue by dchang10** [ptiede/Comrade.jl#178]
A change in commit cdbcc6b11117632d5b3f3cee22604d378cfa7af2 causes `intensitymap` to fail when called on models that are defined with caches. The change is on around line 86 of of src/models/modelimage/nfft_alg.jl where,

```
@inline function create_cache(alg::ObservedNUFT{<:NFFTAlg}, plan, phases, img)
    timg = IntensityMap(transpose(img.im), img.fovx, img.fovy, img.pulse)
    return NUFTCache(alg, plan, phases, img.pulse, timg)
```

was changed to 

```
@inline function create_cache(alg::ObservedNUFT{<:NFFTAlg}, plan, phases, img)
    #timg = #IntensityMap(transpose(img.im), img.fovx, img.fovy, img.pulse)
    return NUFTCache(alg, plan, phases, img.pulse, img.im')
```

**Comment by ptiede** [comment]
A quick update on this. #169 fixed this as a side project. I am going to add this to a test to make sure that I don't mess this up again in the future.
