### ISSUE TITLE
DensityInterface.jl link in Docs for Comrade.Posterior has a typo

### ISSUE THREAD

**Issue by rohandahale** [ptiede/Comrade.jl#182]
https://github.com/ptiede/Comrade.jl/blob/ab8d15cbd210537503a210adedb416bffe9a2ccd/src/bayes/bayes.jl#LL16-L37

DensityInterface points to https://github.com/JuliaMath/DensityInferface.jl instead of https://github.com/JuliaMath/DensityInterface.jl

**Comment by ptiede** [comment]
Solved in #188
