### ISSUE TITLE
Error when using Python backend for Plots.jl?

### ISSUE THREAD

**Issue by saopeter** [ptiede/Comrade.jl#184]
~~Note: It's been a few weeks since I last ran into this issue, so it's possible that there was a patch pushed somewhere upstream that fixed it, though I don't see anything in recent Comrade commits that might have affected it. I'm leaving this here for posterity in case it's helpful to someone, or in case there's a regression. Feel free to close if this is no longer an issue.~~ Update: it happened again today, when I grabbed and ran a fresh copy of the code in this repository: https://github.com/saopeter/challenge1_comrade

I have previously encountered the following error when trying to run https://github.com/ptiede/Comrade.jl/blob/main/examples/imaging.jl directly from a terminal:

```
** (process:95014): WARNING **: 14:01:35.389: Failed to load shared library 'libpango-1.0.so.0' referenced by the typelib: /usr/lib/libpango-1.0.so.0: undefined symbol: hb_ot_layout_get_horizontal_baseline_tag_for_script
ERROR: PyError (PyImport_ImportModule) <class 'AssertionError'>
```

This seems to be related to the issue mentioned here: https://github.com/JuliaPlots/Plots.jl/issues/4282

A possible workaround is to first start a Julia REPL and manually type in the following commands:
```
using Comrade
load_ehtim()
include("imaging.jl")
```
then the `imaging.jl` script will run as expected.

**Comment by ptiede** [comment]
We can't fix this in Comrade since this is an upstream issue. I'll leave this open for now but I can't really act on it.
