### ISSUE TITLE
save function switches the image size in x and y direction

### ISSUE THREAD

**Issue by rohandahale** [ptiede/Comrade.jl#186]
NAXIS1 and NAXIS2 in saving fits seems to be swapped in https://github.com/ptiede/Comrade.jl/blob/32ecaf3aff907d35e21c26e66618ac8d91014486/src/observations/io.jl#LL68-L73

So even if FOV is correct in x and y, number of pixels are most likely exchanged for x and y.

**Comment by ptiede** [comment]
This should be fixed
