### ISSUE TITLE
Typo in example of dev docs for AHMC autodiff in sampling

### ISSUE THREAD

**Issue by rohandahale** [ptiede/Comrade.jl#290]
Dev docs for example: https://ptiede.github.io/Comrade.jl/dev/examples/imaging_vis/

In `chain, stats = sample(rng, post, AHMC(;metric, autodiff=AD.ZygoteBackend()), 400; nadapts=300, init_params=x0)` , ` AHMC(;metric, autodiff=AD.ZygoteBackend())` does not work and should be changed to `AHMC(;metric, autodiff=Val(:Zygote))`

**Comment by ptiede** [comment]
fixed
