### ISSUE TITLE
Make HMC sampler resumable

### ISSUE THREAD

**Issue by kazuakiyama** [ptiede/Comrade.jl#337]
The current `sample` method can save checkpoints with scans of chains and tuned HMC sampler configurations in disk, but doesn't support resuming from a checkpoint. The application of comrade HMC samplers will get wider if it has an option to resume a previous run from a checkpoint, as this allows a long run often chucked in multiple MCMC runs.

**Comment by ptiede** [comment]
So looking through the code it appears I actually did implement this, I just never tested it. Could you try passing `restart=true` to the sample function and see if it resumes?

**Comment by ptiede** [comment]
@kazuakiyama, my local testing seems to suggest the current functionality works. One thing that is missing is changing the number of samples you want. That was just added in commit 1ca888ee35ee4f41cfdf37aa6964f5db3ca32849 and will be included in the next release which will likely get tagged tonight

**Comment by kazuakiyama** [comment]
Thanks a lot! We will test it in the next few days, and let you know if we find anything.
